<?php


/**
 * Manage top navbar elements.
 * 
 * @extends ViewModel
 */
class View_Header extends ViewModel {
	
	public $_view = 'layouts.header';
	public $current_section = null;
	public $sorter = null;
	
	
	/**
	 * Set Header elements, like search form, sort / user dropdown
	 * and section refresh button.
	 * 
	 * @access public
	 * @return void
	 */
	public function view()
	{
		// Sortable dropdown, generated by public controller
		if ($this->sorter)
		{
			$content[] = $this->sorter['drop'];
			//$content[] = $this->sorter['dir'];
		}
		
		// Refresh section link
		if ($this->current_section)
		{
			$icon		= html_tag('i', array('class' => 'icon icon-white icon-refresh'), '');
			$anchor = Html::anchor(To::section($this->current_section, 'refresh'), $icon.' '.__('app.refresh_section'), array(
				'class' => 'nav-icon',
				'id'		=> 'section-refresh',
				'data-status-url' => '/'.To::section($this->current_section, 'refresh_status')
			));
			$content[] = html_tag('li', array(), $anchor);
			
			$this->search_action = To::section($this->current_section);
		}
		
		// User Dropdown
		$content[] = Html::dropdown(Auth::get_screen_name(), array(
			array(Uri::base().'parameters', __('app.parameters'), array('icon' => 'cog')),
			array(Uri::base().'login/logout', __('app.logout'), array('icon' => 'off'))
		), array(), 'li');
				
		// Build list
		$this->right_items = html_tag('ul', array('class' => 'nav pull-right'), implode($content));
		
		$this->title = APPNAME;
	}
	
}